# Generated by Django 4.1.1 on 2022-09-15 08:26

from django.db import migrations
import django_popularity.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mid',
            field=django_popularity.fields.MIDField(blank=True, max_length=100, unique=True),
        ),
    ]
