# Generated by Django 4.1.1 on 2022-09-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_alter_person_mid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('geo', models.CharField(max_length=255)),
                ('score1080', models.FloatField()),
                ('score180', models.FloatField()),
                ('score30', models.FloatField()),
                ('score360', models.FloatField()),
                ('score90', models.FloatField()),
            ],
            options={
                'db_table': 'django_popularity_popularity',
                'managed': False,
            },
        ),
    ]
