# Generated by Django 4.0.5 on 2022-09-21 09:09

from django.db import migrations
import django_popularity.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_personpopularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mid',
            field=django_popularity.fields.MIDField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
