# Generated by Django 4.1.1 on 2022-09-08 12:38

from django.db import migrations, models
import django.db.models.deletion
import django_popularity.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_action_reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', models.CharField(choices=[('US', 'US'), ('JP', 'JP'), ('GB', 'GB'), ('FR', 'FR'), ('DE', 'DE'), ('TH', 'TH'), ('SG', 'SG'), ('IT', 'IT'), ('KR', 'KR')], max_length=100, unique=True)),
                ('top_mid', django_popularity.fields.MIDField(max_length=100)),
                ('top_title', models.CharField(max_length=100)),
                ('top_type', models.CharField(max_length=100)),
                ('bot_mid', django_popularity.fields.MIDField(max_length=100)),
                ('bot_title', models.CharField(max_length=100)),
                ('bot_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('geo', models.CharField(max_length=255)),
                ('graph', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='popularity', to='django_popularity.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuggestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('mid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('geo', models.CharField(max_length=255)),
                ('is_top', models.BooleanField()),
                ('graph', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='standard', to='django_popularity.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PopularityActionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField()),
                ('action', models.CharField(choices=[('crawl', 'crawl')], max_length=255)),
                ('log', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_action_reservation.actionlog')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='django_popularity.popularity')),
            ],
        ),
        migrations.AddField(
            model_name='popularity',
            name='standard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='popularity1', to='django_popularity.standard'),
        ),
        migrations.AddField(
            model_name='popularity',
            name='standard2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='popularity2', to='django_popularity.standard'),
        ),
        migrations.CreateModel(
            name='DateGraphPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_points', to='django_popularity.graph')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
