# Generated by Django 4.1.1 on 2022-09-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_popularity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularity',
            name='score1080',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='popularity',
            name='score180',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='popularity',
            name='score30',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='popularity',
            name='score360',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='popularity',
            name='score90',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='standard',
            name='score1080',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='standard',
            name='score180',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='standard',
            name='score30',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='standard',
            name='score360',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='standard',
            name='score90',
            field=models.FloatField(default=0),
        ),
    ]
