# Generated by Django 4.1.1 on 2022-09-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_popularity', '0002_popularity_score1080_popularity_score180_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geostandard',
            name='geo',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('JP', 'JP'), ('GB', 'GB'), ('FR', 'FR'), ('DE', 'DE'), ('TH', 'TH'), ('SG', 'SG'), ('IT', 'IT'), ('KR', 'KR'), ('', 'World wide')], max_length=100, unique=True),
        ),
    ]
