# Generated by Django 4.0.5 on 2022-09-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_popularity', '0003_alter_geostandard_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='geostandard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='geostandard',
            name='geo',
            field=models.CharField(blank=True, choices=[('US', 'US (United States)'), ('JP', 'JP (Japan)'), ('GB', 'GB (United Kingdom)'), ('FR', 'FR (France)'), ('DE', 'DE (Germany)'), ('TH', 'TH (Thaland)'), ('SG', 'SG (Singapore)'), ('IT', 'IT (Italy)'), ('KR', 'KR (Korea)'), ('ES', 'ES (Spain)'), ('IN', 'IN (India)'), ('TR', 'TR (Turkey)'), ('BR', 'BR (Brazil)'), ('MX', 'MX (Mexico)'), ('CA', 'CA (Canada)'), ('AU', 'AU (Australia)'), ('', ' (World wide)')], max_length=100, unique=True),
        ),
    ]
